# Generated by Django 4.2.11 on 2024-05-05 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('on_time_delivery_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quality_rating_avg', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('average_response_time', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fulfillment_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_performances', to='vendor.vendor')),
            ],
        ),
    ]
